CREATE TABLE BRANDS (
    "ID" INT PRIMARY KEY,
    "NAME" varchar(255)
);

CREATE TABLE PRODUCTS (
    "ID" INT PRIMARY KEY,
    "NAME" varchar(255)
);

CREATE TABLE PRICES (
    BRAND_ID INT NOT NULL,
    START_DATE TIMESTAMP(0) NOT NULL,
    END_DATE TIMESTAMP(0) NOT NULL,
    PRICE_LIST INT NOT NULL,
    PRODUCT_ID INT NOT NULL,
    PRIORITY TINYINT NOT NULL,
    PRICE DECIMAL(6,2) NOT NULL,
    CURR CHAR(3) NOT NULL,
    PRIMARY KEY (BRAND_ID,PRODUCT_ID,PRICE_LIST),
    FOREIGN KEY (BRAND_ID) REFERENCES BRANDS(ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(ID)
);